### ISSUE TITLE
DK Stance bar

### ISSUE THREAD

**Issue by StijnDeWinter** [d4kir92/MoveAny#1]
I've noticed the DK stance bar often resets to an odd location.
Currently the addon moves action bar 1 & 2 to the middle bottom of the screen with pet buttons on top. The stance bar often resets to the middle of the screen BEHIND the pet action bar.
I've disabled and/or deleted all other addons that (try to) manage the UI element's location, but to no avail.
Happens even within the same instance when dying (Alterac Valley e.g.)

HMU if I need to test additional things out!

**Comment by StijnDeWinter** [comment]
https://imgur.com/a/dNqdAj0
Here's a screenshot, loaded in AV and this happened.

**Comment by d4kir92** [comment]
in v0.3.0 its fixed, try it pls :D

**Comment by StijnDeWinter** [comment]
It still triggers, however I do not know the circumstances.
I just got a mail saying you updated it so I typed /reload and it moved the stance bar again. However, I got all my other addons activated at the moment, so I do not know whether another addon is interfering...

**Comment by d4kir92** [comment]
make sure you have v0.3.1

**Comment by d4kir92** [comment]
on curse its still not there*

**Comment by d4kir92** [comment]
![image](https://user-images.githubusercontent.com/23246564/189902222-de956c1b-8b5f-4363-8b37-f54b28c5f5e4.png)

**Comment by StijnDeWinter** [comment]
I am unable to reproduce the problem! Hooray! :D

**Comment by d4kir92** [comment]
very nice (:
