### ISSUE TITLE
Default bags stacking.

### ISSUE THREAD

**Issue by Tigon3rd** [d4kir92/MoveAny#10]
MoveAny makes my opened default separated bags stack and not act right, like when closing one the others doesn't move into the place of the just closed one.

In picture 1 I have opened all my bags at once with "Shift-B" and one of the bags is hidden behind another.
![1](https://user-images.githubusercontent.com/9333263/205445392-a57f522d-ee72-4dda-9fc5-71681c3c5876.jpg)

In picture 2 I have closed the 3rd bag and the 2nd is now visible from below.
![2](https://user-images.githubusercontent.com/9333263/205445485-1218dc35-a10c-4e84-a2d3-e86d3465cf6b.jpg)

In picture 3 I close the 2nd bag and the others don't move, except the new reagent bag, which also moved from picture 1 to 2 and then back in 3 and is also overlapping with bag 4.
![3](https://user-images.githubusercontent.com/9333263/205445596-704d3d7a-2161-486c-bb4e-2584228be6e4.jpg)

**Comment by d4kir92** [comment]
when you moved a bag accidentally, it behave like this, just reset all 5 frames with MiddleMouseDrag on the borders of that frames till the chat says that the frame is reset, after reset all 5 you can reopen it and it should behave normally
