### ISSUE TITLE
Map selection off-center with other map addons after update

### ISSUE THREAD

**Issue by Nicktentjr** [d4kir92/MoveAny#11]
I use the Mapster addon, and up until the recent update it's been able to function fine with MoveAny. However, since the update to MoveAny, the zone selection is no longer centered on the mouse and is instead offset to the left, as if interacting with the default-sized map. For example, in order to select Desolace, I have to hover over Mulgore instead. This issue is only resolved by turning off MoveAny.

**Comment by d4kir92** [comment]
on Wrath?

**Comment by Nicktentjr** [comment]
Yes

**Comment by d4kir92** [comment]
should work now
