### ISSUE TITLE
Separate UI Error message and Quest progress?

### ISSUE THREAD

**Issue by Miha23833** [d4kir92/MoveAny#13]
I have some problems with my addons, they raise a lot of errors in Lua code which causes showing UI Error message tray. I hide it with this addon but I hide quest progress too and I think it's not good. Is there any way to separate these trays or hide only UI Error message without hiding quest progress?

WoW: WotLK classic
Addon version: 1.0.52

**Comment by d4kir92** [comment]
the ui errors also shows quest progress, idk why blizzard done this, but cant be seperated.
But i think its possible to disable the red messages somewhere
