### ISSUE TITLE
WoW classic: "RightClickSelfCast" not working with all ActionBars

### ISSUE THREAD

**Issue by AzucarSalado** [d4kir92/MoveAny#15]
HI, I am using "RightClickSelfCast" with "MoveAny". It allows to cast on self when you right click on the bar regardless of the target you have. It happens that:

- It still works with what MoveAny calls Actionbars 1 + 5 +6. But,
- It does not work with the rest of the bars: bars nº 3 (right bar), nº 4 (left bar), 7, 8, 9.

If I disable MoveAny, it perfectly works on all bars. I have not found any configuration option in "MoveAny" for this behavior, sorry if it exits and I am blind. Could you give any help?

Cheers,

**Comment by d4kir92** [comment]
i added this to my other addon "ImproveAny"

![image](https://user-images.githubusercontent.com/23246564/236678801-57e6bb91-0572-4b7a-8690-779794d2fad3.png)

**Comment by d4kir92** [comment]
v0.7.6 ImproveAny*

**Comment by AzucarSalado** [comment]
HI, Think you for your work. The right click self cast of "ImproveAny" with "MoveAny" is working. Nevertheless, ImproveAny has too many options that I don't use. I think I'll have to macro all casts. Thank you.

**Comment by d4kir92** [comment]
Well If you disable everything in improveany except this it would only do that
