### ISSUE TITLE
there is no options window and get some lua errors

### ISSUE THREAD

**Issue by AzucarSalado** [d4kir92/MoveAny#17]
Hello,

I noticed with today's update that when I right click someplaces in my window, it opens a void menu window called MABuffBar. Then, I noticed that MA's mini map icon is not shown and that the options window for MA is not shown when you type /move or /moveany, 

This is what it shows when I type /move:

![WoWScrnShot_051623_194602](https://github.com/d4kir92/MoveAny/assets/63239138/327184df-b020-485e-8606-110821e564cf)

And this is a screenshot with the add-ons I left activated and the MABUffeBar void window:

![WoWScrnShot_051623_193905](https://github.com/d4kir92/MoveAny/assets/63239138/8fd77faf-288c-4991-92d1-e500d97dc31a)
 
BugGrabber cathed these errors:

8x Interface\AddOns\MoveAny\core.lua:54: attempt to index global 'MALock' (a nil value)
[string "@Interface\AddOns\MoveAny\core.lua"]:54: in function `?'
[string "@Interface\AddOns\MoveAny\core.lua"]:102: in function <Interface\AddOns\MoveAny\core.lua:87>
[string "=[C]"]: in function `ChatFrame_DisplayHelpTextSimple'
[string "@Interface\FrameXML\ChatFrame.lua"]:4917: in function <Interface\FrameXML\ChatFrame.lua:4846>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4563: in function <Interface\FrameXML\ChatFrame.lua:4562>
[string "=[C]"]: in function `ChatEdit_SendText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4599: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
self = nil
(*temporary) = nil
(*temporary) = <table> {
 SetCP = <function> defined @Interface\AddOns\MoveAny\libs/db.lua:56
 LangzhCN = <function> defined @Interface\AddOns\MoveAny\locale/zhCN.lua:4
 Grid = <function> defined @Interface\AddOns\MoveAny\libs/math.lua:42
 AnyActionbarEnabled = <function> defined @Interface\AddOns\MoveAny\registerwidgets.lua:942
 CustomBars = <function> defined @Interface\AddOns\MoveAny\ele/actionbars.lua:258
 GetFramePoint = <function> defined @Interface\AddOns\MoveAny\libs/db.lua:527
 InitArenaEnemyFrames = <function> defined @Interface\AddOns\MoveAny\ele/arenaenemyframes.lua:3
 InitBags = <function> defined @Interface\AddOns\MoveAny\ele/bagbar.lua:76
 LangruRU = <function> defined @Interface\AddOns\MoveAny\locale/ruRU.lua:4
 UpdateActionBar = <function> defined @Interface\AddOns\MoveAny\ele/actionbars.lua:26
 InitMultiCastActionBar = <function> defined @Interface\AddOns\MoveAny\ele/multicastactionbar.lua:3
 GetTab = <function> defined @Interface\AddOns\MoveAny\libs/db.lua:247
 UpdateLanguage = <function> defined @Interface\AddOns\MoveAny\libs/lang.lua:25
 GetDragFrames = <function> defined @Interface\AddOns\MoveAny\core.lua:16
 LangenUS = <function> defined @Interface\AddOns\MoveAny\locale/enUS.lua:10
 UpdateABs = <function> defined @Interface\AddOns\MoveAny\ele/actionbars.lua:395
 GetProfiles = <function> defined @Interface\AddOns\MoveAny\libs/db.lua:133
 EnableSave = <function> defined @Interface\AddOns\MoveAny\malock.lua:264
 IsEnabled = <function> defined @Interface\AddOns\MoveAny\libs/db.lua:368
 SetEleSize = <function> defined @Interface\AddOns\MoveAny\libs/db.lua:477
 SetEnabled = <function> defined @Interface\AddOns\MoveAny\libs/db.lua:345
 UpdateBags = <function> defined @Interface\AddOns\MoveAny\ele/bagbar.lua:17
 GetEleScale = <function> defined @Interface\AddOns\MoveAny\libs/db.lua:485
 InitActionBarLayouts = <function> defined @Interface\AddOns\MoveAny\ele/actionbars.lua:233
 ImportProfile = <function> defined @Interface\AddOns\MoveAny\libs/db.lua:96
 LangdeDE = <function> defined @Interface\AddOns\MoveAny\locale/deDE.lua:4
 GetEleSize = <function> defined @Interface\AddOns\MoveAny\libs/db.lua:466
 CreateSlider = <function> defined @Interface\AddOns\MoveAny\registerwidgets.lua:88
 init = true
 GetFrameScale = <function> defined @Interface\AddOns\MoveAny\libs/db.lua:550
 SetEleAlpha = <function> defined @Interface\AddOns\MoveAny\registerwidgets.lua:868
 SetEleScale = <function> defined @Interface\AddOns\MoveAny\libs/db.lua:503
 ToggleMinimapButton = <function> defined @Interface\AddOns\MoveAny\registerwidgets.lua:428
 SetFrameScale = <function> defined @Interface\AddOns\MoveAny\libs/db.lua:558
 InitMALock = <function> defined @Interface\AddOns\MoveAny\malock.lua:278
 GetWoWBuildNr = <function> defined @Interface\AddOns\MoveAny\libs/math.lua:13
 IsInEditModeEnabled = <function> defined @Interface\AddOns\MoveAny\malock.lua:86
 MoveFrames = <function> defined @Interface\AddOns\MoveAny\moveframes.lua:358
 MathC = <function> defined @Interface\AddOns\MoveAny\libs/math.lua:21
 Event = <function> defined @Interface\AddOns\MoveAny\registerwidgets.lua:950
 AddToEMMap = <function> defined @Interface\AddOns\MoveAny\malock.lua:54
 BAGSTryAdd = <function> defined @Interface\AddOns\MoveAny\ele/bagbar.lua:5
 RemoveProfile = <function> defined @Interface\AddOns\MoveAny\libs/db.lua:90
 GT = <function> defined @Interface\AddOns\MoveAny\libs/lang.lua:10
 MSG = <function> defined @Interface\AddOns\MoveAny\libs/db.lua:14
 AddToEMMapForced = <function> defined @Interface\AddOns\MoveAny\malock.lua:24
 UpdateLanguageTab = <function> defined @Interface\AddOns\MoveAny\locale/enUS.lua:4
 InitSlash = <function> defined @Interface\AddOns\MoveAny\core.lua:107
 UpdateMoveFrames = <function> defined @Interface\AddOns\MoveAny\moveframes.lua:112
 IImportSizesValue = <function> defined @Interface\AddOns\MoveAny\libs/db.lua:174
 RenameProfile = <function> defined @Interface\AddOns\MoveAny\libs/db.lua:105
 GetElePoint = <function> defined @Interface\AddOns\MoveAny\libs/db.lua:418
 UpdateCurrentFrame = <function>

Thanks,

**Comment by d4kir92** [comment]
v1.1.22 should fix it

**Comment by AzucarSalado** [comment]
I does. You are fast ;-)

Thanks.-
