### ISSUE TITLE
How to move FPS counter?

### ISSUE THREAD

**Issue by scalp42** [d4kir92/MoveAny#2]
Hi @d4kir92 

I'm trying to move away from [MoveAnything](https://www.curseforge.com/wow/addons/move-anythin) but one feature that was very useful is that you could move the FPS counter wherever you wanted.

Any idea if it's possible with MoveAny?

Thank you in advance!

**Comment by d4kir92** [comment]
ImproveAny has a custom one, because the blizz one is tainting/error and doesn't look that good :D
