### ISSUE TITLE
v1.5.4 issues with target of target and minimap button

### ISSUE THREAD

**Issue by Xorag** [d4kir92/MoveAny#21]
Hello, the latest update appears to be causing the blizzard target of target frame to always be hidden when moved to a custom location. Also upon reloading the ui/enabling the addon my minimap button keeps reappearing after hiding it.

**Comment by Xorag** [comment]
![image](https://github.com/d4kir92/MoveAny/assets/42698965/a1b625b8-cbee-4b4f-ba2e-80a7d1b40863)

Frame missing while in combat:
![image](https://github.com/d4kir92/MoveAny/assets/42698965/51b3d88a-b533-4c1e-a26b-889c3341606f)

**Comment by d4kir92** [comment]
v1.5.5

**Comment by Xorag** [comment]
Target frame is back but minimap button keeps reappearing on /reload, thanks!

**Comment by d4kir92** [comment]
v1.5.7

**Comment by Xorag** [comment]
seems fixed, thanks!
