### ISSUE TITLE
Some UI elements not hiding when pressing alt-z on WotLK

### ISSUE THREAD

**Issue by johanbv** [d4kir92/MoveAny#23]
Hey, when pressing the keybind to hide the UI, some elements still showing.

## Normal:
![image](https://github.com/d4kir92/MoveAny/assets/32653302/55b0fc6f-728d-44b4-87c5-889722c4bf90)

## Alt-z:
![image](https://github.com/d4kir92/MoveAny/assets/32653302/1312656d-91bf-4c55-ab6b-d679be319f6b)

Thank you for the work on the addon, is quite useful for me.

**Comment by d4kir92** [comment]
should work with latest

**Comment by johanbv** [comment]
> should work with latest

Yeah, it works now.

Thank you!
