### ISSUE TITLE
TalkingHeadDialog anchor can't be moved or interacted with

### ISSUE THREAD

**Issue by LazinessEvolved** [d4kir92/MoveAny#24]
Sorry if this report is super lightweight.

After recent updates I noticed that the THD is sort of "under-popped" in the MoveAny grid, it can't be dragged around or resized or selected in any way. Yet it pushes it down to the lower middle of the screen, over top of the action bars, which is nowhere near the pre-patch location of the dialog.

I have tried reloads and turning on/off various other addons, but it persists in this location for now and can't be moved.

**Comment by d4kir92** [comment]
is it red?

**Comment by d4kir92** [comment]
works for me on latest version

**Comment by LazinessEvolved** [comment]
It isn't red. It's the large rectangle. top right. Can't be clicked or interacted with. I disabled other addons to be sure it was not interference. All other frames can be moused over and moved, but not this one.

![image](https://github.com/d4kir92/MoveAny/assets/78278321/0a999350-e230-42f8-9560-b6f476e1a67a)

**Comment by d4kir92** [comment]
try start game, go in a character, restart game, if still not movable please let me know

**Comment by LazinessEvolved** [comment]
Okay, so I was able to resolve this in this way:

- Disabled all addons
- Reloaded UI
- Opened Blizzard default "Edit Mode" and was able to move the anchor.
- Enabled MoveAny, was able to drag the box from there again!
- Re-enabled other addons, things seem fine now.

Sorry if this was more noise than help. It was just odd that no other frames had issues. That Talking Head Dialog is the most obnoxious thing in the game, frankly, especially its interactions with addons.

Thanks for your responses!

**Comment by d4kir92** [comment]
talking head had this problem versions ago, so it kindy comes back, idk why
