### ISSUE TITLE
Any wiki, tutorial or command list?

### ISSUE THREAD

**Issue by comonier** [d4kir92/MoveAny#25]
I've just installed the addon but I haven't found any tutorials on the commands to lock or unlock the interface for moving the addon's move options. The only option that appears is to open the menu and check or uncheck things, but none of the things can be moved, and apparently it stays on the screen with the grid locked. How unlock? 

I just need the addon to try move battlegrond stats:
![image](https://github.com/d4kir92/MoveAny/assets/19571541/51be343c-2380-4b57-b8ea-d7eb3fefc81f)
I would like to know if your addon allows you to **move the battlergound stats**, if it doesn't, it's not for me.

**Comment by d4kir92** [comment]
I try to improve the search bar, thanks for the new words

/Moveany -> Check: Widget Center -> reload -> move -> save -> X

Widget Center move more then Just this, its a collect of Things Blizzard want to use there

**Comment by d4kir92** [comment]
On the top is the searchbar

**Comment by d4kir92** [comment]
changed the name in moveany

Widget Top Center (Status/Stats on Battlegrounds/Dungeons/Raids)

hope this is better, any suggestions are welcome
