### ISSUE TITLE
Mocking BagsBar causes errors in other addons

### ISSUE THREAD

**Issue by Hati-** [d4kir92/MoveAny#26]
Some addons expects `BagsBar` to be the frame provided by Dragonflight's new editable UI. This addons mocks this frame variable in classic which causes errors in other addons:
https://github.com/d4kir92/MoveAny/blob/164e98f0b329553a1abee48db6e7e3eeb3be09e8/ele/bagbar.lua#L93C21-L96

I wrote how this caused an error in the Dominos addon here:
https://github.com/tullamods/Dominos/issues/766#issuecomment-1678365305

You should either use a different variable name or find a way to not mock `BagsBar` to prevent incompatibilities with other addons. I haven't checked the entire code but if it mocks any other Blizzard UI frames then you probably shouldn't do that either.

**Comment by d4kir92** [comment]
MoveAny is now compatible with Dominos:
v1.6.8+
