### ISSUE TITLE
Option to suppress shared frame warning at log in

### ISSUE THREAD

**Issue by Xorag** [d4kir92/MoveAny#27]
Hello, is it possible to have an option to hide this warning when logging into the game?

![image](https://github.com/d4kir92/MoveAny/assets/42698965/7d8f0612-e062-4697-8111-34c9644fc35d)

Thanks!

**Comment by d4kir92** [comment]
v1.6.15+

**Comment by d4kir92** [comment]
should be hidden when you uncheck "show tips"
