### ISSUE TITLE
10.1.7 Lua Error when entering combat

### ISSUE THREAD

**Issue by Xorag** [d4kir92/MoveAny#28]
Hello! Please see the below error when entering combat for the first time on reload or log-in. Thanks!

`1x [ADDON_ACTION_BLOCKED] AddOn 'MoveAny' tried to call the protected function 'StatusBar:Show()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `Show'
[string "@FrameXML/TextStatusBar.lua"]:82: in function `TextStatusBar_UpdateTextStringWithValues'
[string "@FrameXML/TextStatusBar.lua"]:68: in function `TextStatusBar_UpdateTextString'
[string "@FrameXML/TextStatusBar.lua"]:183: in function `TextStatusBar_OnValueChanged'
[string "@FrameXML/UnitFrame.lua"]:925: in function `UnitFrameHealthBar_OnValueChanged'
[string "@FrameXML/TargetFrame.lua"]:1052: in function <FrameXML/TargetFrame.lua:1051>
[string "=[C]"]: in function `SetValue'
[string "@FrameXML/UnitFrame.lua"]:916: in function `UnitFrameHealthBar_Update'
[string "@FrameXML/UnitFrame.lua"]:231: in function `UnitFrame_Update'
[string "@FrameXML/TargetFrame.lua"]:132: in function `Update'
[string "@FrameXML/TargetFrame.lua"]:162: in function `OnEvent'
...
[string "=[C]"]: in function `UseAction'
[string "@FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@FrameXML/SecureTemplates.lua"]:690: in function <FrameXML/SecureTemplates.lua:672>
[string "@FrameXML/SecureTemplates.lua"]:704: in function <FrameXML/SecureTemplates.lua:697>
[string "@FrameXML/SecureTemplates.lua"]:746: in function <FrameXML/SecureTemplates.lua:730>
[string "=[C]"]: ?
[string "@FrameXML/SecureHandlers.lua"]:266: in function <FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@FrameXML/SecureHandlers.lua"]:296: in function <FrameXML/SecureHandlers.lua:279>
[string "=(tail call)"]: ?

Locals:
Skipped (In Encounter)`

**Comment by d4kir92** [comment]
does this also happen with moveany only enabled?
---
do you have something checked in
"Advanced" section?
![image](https://github.com/d4kir92/MoveAny/assets/23246564/22cdea9c-bfdd-48c7-9719-22b9ac282065)

**Comment by d4kir92** [comment]
please try v1.6.26 first

**Comment by Xorag** [comment]
Yes seems to be fixed with the new version, sorry for the lack of info. I use target of target under normal, and I hide totems and move target cast bar under advanced. Thanks as always!
