### ISSUE TITLE
Mounts -> Appearances

### ISSUE THREAD

**Issue by BlindsidedGames** [d4kir92/MoveAny#3]
Hi, I switched to MoveAny beacuse MoveAnything sucks. Great work.
I have an ultrawide and being able to move these windows is super important to me.

Any chance you could add support for the Mounts, Pets, Toy< Heirloom, appearance window?

**Comment by d4kir92** [comment]
this frame is secured by blizz
i didn't found a solution to move it yet
with the current system if you try to move it it is stucked/bugged

**Comment by BlindsidedGames** [comment]
How does elvui do it?

**Comment by d4kir92** [comment]
do they? :O

**Comment by d4kir92** [comment]
i can move it via an extra frame, but then you cant see how it looks like till you release the mouse click

**Comment by BlindsidedGames** [comment]
> i can move it via an extra frame, but then you cant see how it looks like till you release the mouse click

I would be totally okay with that

**Comment by d4kir92** [comment]
ok i got a solution with preview, next update has it :D
