### ISSUE TITLE
IsCtrlKeyDown error

### ISSUE THREAD

**Issue by Bendder** [d4kir92/MoveAny#30]
Here's the bugsack for the error:  (Unfortunately the end of the local stack is clipped short)

7x MoveAny/settings.lua:346: attempt to call global 'IsCtrlKeyDown' (a nil value)
[string "@MoveAny/settings.lua"]:346: in function `IsFrameKeyDown'
[string "@MoveAny/moveframes.lua"]:221: in function <MoveAny/moveframes.lua:201>

Locals:
self = <table> {
 SetCP = <function> defined @MoveAny/libs/db.lua:53
 UpdateAlpha = <function> defined @MoveAny/registerwidgets.lua:1461
 LangzhCN = <function> defined @MoveAny/locale/zhCN.lua:3
 UpdateElementList = <function> defined @MoveAny/settings.lua:407
 AnyActionbarEnabled = <function> defined @MoveAny/registerwidgets.lua:1504
 GetFrameName = <function> defined @MoveAny/registerwidgets.lua:36
 CustomBars = <function> defined @MoveAny/ele/actionbars.lua:248
 GetColor = <function> defined @MoveAny/core.lua:14
 InitArenaEnemyFrames = <function> defined @MoveAny/ele/arenaenemyframes.lua:3
 InitBags = <function> defined @MoveAny/ele/bagbar.lua:92
 LangruRU = <function> defined @MoveAny/locale/ruRU.lua:3
 UpdateActionBar = <function> defined @MoveAny/ele/actionbars.lua:28
 init = true
 UpdateLanguage = <function> defined @MoveAny/libs/lang.lua:25
 GetDragFrames = <function> defined @MoveAny/core.lua:20
 LangenUS = <function> defined @MoveAny/locale/enUS.lua:9
 GetCurrentEle = <function> defined @MoveAny/registerwidgets.lua:4
 EnableSave = <function> defined @MoveAny/settings.lua:328
 IsEnabled = <function> defined @MoveAny/libs/db.lua:286
 CheckSave = <function> defined @MoveAny/moveframes.lua:165
 AddFrameName = <function> defined @MoveAny/registerwidgets.lua:18
 ImportProfile = <function> defined @MoveAny/libs/db.lua:92
 Lock = <function> defined @MoveAny/core.lua:120
 GetFrameScale = <function> defined @MoveAny/libs/db.lua:513
 GetMicroButtonYOffset = <function> defined @MoveAny/ele/micromenu.lua:9
 SetFrameScale = <function> defined @MoveAny/libs/db.lua:521
 GetWoWBuildNr = <function> defined @MoveAny/libs/math.lua:13
 MoveFrames = <function> defined @MoveAny/moveframes.lua:371
 UpdateFrameKeybind = <function> defined @MoveAny/settings.lua:401
 InitPartyFrame = <function> defined @MoveAny/ele/partyframe.lua:3
 SetMouseEleAlpha = <function> defined @MoveAny/registerwidgets.lua:1401
 ShowMinimapButton = <function> defined @MoveAny/settings.lua:4031
 IImportPointValue = <function> defined @MoveAny/libs/db.lua:132
 UpdateLanguageTab = <function> defined @MoveAny/locale/enUS.lua:3
 Snap = <function> defined @MoveAny/libs/math.lua:42
 InitMinimap = <function> defined @MoveAny/ele/minimap.lua:3
 GetElePoint = <function> defined @MoveAny/libs/db.lua:359
 UpdateStanceBar = <function> defined @MoveAny/ele/stancebar.lua:16
 GetMinimapTable = <function> defined @MoveAny/libs/db.lua:527
 ShowProfiles = <function> defined @MoveAny/settings.lua:936
 GetWoWBuild = <function> defined @MoveAny/libs/math.lua:17
 LangesES = <function> defined @MoveAny/locale/esES.lua:3
 UnlockBindings = <function> defined @MoveAny/core.lua:75
 InitMicroMenu = <function> defined @MoveAny/ele/micromenu.lua:15
 GetMainPanel = <function> defined @MoveAny/core.lua:64
 ToggleMALock = <function> defined @MoveAny/core.lua:191
 InitDB = <function> defined @MoveAny/libs/db.lua:546
 InitMAFPSFrame = <function> defined @MoveAny/ele/fps.lua:4
 InitArenaPrepFrames = <function> defined @MoveAny/ele/arenaenemyframes.lua:58
 LangptBR = <function> defined @MoveAny/locale/ptBR.lua:3
 GetAlphaFrames = <function> defined @MoveAny/registerwidgets.lua:13
 SetElePoint = <function> defined @MoveAny/libs/db.lua:378
 LockBindi

**Comment by d4kir92** [comment]
thx for the info
