### ISSUE TITLE
Cannot Purchase in Trading post

### ISSUE THREAD

**Issue by rionshin** [d4kir92/MoveAny#31]
When i click Purchase in trading post - I  am getting this error, if i disable MoveAny  everything is working fine. :

17x Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: StaticPopup1:SetPoint.
[string "=[C]"]: ?
[string "=[C]"]: in function `SetPoint'
[string "@FrameXML/StaticPopup.lua"]:5412: in function `StaticPopup_SetUpAnchor'
[string "@FrameXML/StaticPopup.lua"]:5400: in function <FrameXML/StaticPopup.lua:5398>
[string "=[C]"]: in function `StaticPopup_SetUpPosition'
[string "@FrameXML/StaticPopup.lua"]:5014: in function <FrameXML/StaticPopup.lua:4539>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `StaticPopup_Show'
[string "@Blizzard_PerksProgram/Blizzard_PerksProgram.lua"]:286: in function `?'
[string "@Blizzard_PerksProgram/Blizzard_PerksProgramElements.lua"]:502: in function <...zzard_PerksProgram/Blizzard_PerksProgramElements.lua:499>

Locals:
(*temporary) = StaticPopup1 {
 0 = <userdata>
 hideOnEscape = true
 SubText = FontString {
 }
 ItemFrame = StaticPopup1ItemFrame {
 }
 Border = Frame {
 }
 DarkOverlay = Frame {
 }
 DropDownControl = Frame {
 }
 button4 = StaticPopup1Button4 {
 }
 moneyFrame = StaticPopup1MoneyFrame {
 }
 text = StaticPopup1Text {
 }
 extraButton = StaticPopup1ExtraButton {
 }
 maxHeightSoFar = 140.483756
 CoverFrame = Frame {
 }
 itemFrame = StaticPopup1ItemFrame {
 }
 enterClicksFirstButton = true
 data = <table> {
 }
 button3 = StaticPopup1Button3 {
 }
 numButtons = 2
 extraFrame = StaticPopup1ExtraFrame {
 }
 exclusive = 1
 SetPoint = <function> defined =[C]:-1
 maxWidthSoFar = 320
 button2 = StaticPopup1Button2 {
 }
 LoadingSpinner = Frame {
 }
 SetScale = <function> defined =[C]:-1
 moneyInputFrame = StaticPopup1MoneyInputFrame {
 }
 button1 = StaticPopup1Button1 {
 }
 maframesetpoint = false
 AlertIcon = StaticPopup1AlertIcon {
 }
 editBox = StaticPopup1EditBox {
 }
 timeleft = 0
 CloseButton = StaticPopup1CloseButton {
 }
 SpinnerAnim = AnimationGroup {
 }
 Separator = Texture {
 }
 masetscale_frame = false
 icon = StaticPopup1AlertIcon {
 }
 onCloseCallback = <function> defined @FrameXML/StaticPopup.lua:5252
 which = "PERKS_PROGRAM_CONFIRM_PURCHASE"
}
(*temporary) = "TOP"
(*temporary) = PerksProgramFrame {
 0 = <userdata>
 TimeLeftFooterFormatter = <table> {
 }
 GetHideArmorSetting = <function> defined @Blizzard_PerksProgram/Blizzard_PerksProgram.lua:99
 SelectPreviousProduct = <function> defined @Blizzard_PerksProgram/Blizzard_PerksProgram.lua:151
 PlayerToggledHideArmorOnClick = <function> defined @Blizzard_PerksProgram/Blizzard_PerksProgram.lua:104
 sortField = "price"
 OnKeyDown = <function> defined @Blizzard_PerksProgram/Blizzard_PerksProgram.lua:256
 OnServerRefundCountdownExpired = <function> defined @Blizzard_PerksProgram/Blizzard_PerksProgram.lua:318
 SetHideArmorSetting = <function> defined @Blizzard_PerksProgram/Blizzard_PerksProgram.lua:95
 OnShow = <function> defined @Blizzard_PerksProgram/Blizzard_PerksProgram.lua:187
 TimeLeftListFormatter = <table> {
 }
 OnFrozenItemConfirmationShown = <function> defined @Blizzard_PerksProgram/Blizzard_PerksProgram.lua:331
 SetSortField = <function> defined @Blizzard_PerksProgram/Blizzard_PerksProgram.lua:62
 Purchase = <function> defined @Blizzard_PerksProgram/Blizzard_PerksProgram.lua:294
 maxScale = 0.750000
 SetUseNativeForm = <function> defined @Blizzard_PerksProgram/Blizzard_PerksProgram.lua:126
 activeFilters = <table> {
 }
 ConfirmPurchase = <function> defined @Blizzard_PerksProgram/Blizzard_PerksProgram.lua:274
 vendorItemIDs = <table> {
 }
 ThemeContainer = Frame {
 }
 GetFrozenPerksVendorItemInfo = <function> defined @Blizzard_PerksProgram/Blizzard_PerksProgram.lua:398
 Leave = <function> defined @Blizzard_PerksProgram/Blizzard_PerksProgram.lua:269
 GetUseNativeForm = <function> defined @Blizzard_PerksProgram/Blizzard_PerksProgram.lua:122
 GetSortField = <function> defined @Blizzard_PerksProgram/Blizzard_PerksProgram.lua:74
 GetCategories = <function> defined @Blizzard_PerksProgram/Blizzard_PerksProgram.lua:139
 currencyIconMarkup = "|T4696085:20:20:0:0:64:64:0:64:0:64|t"
 OnLoad = <function> defined @Blizzard_PerksProgram/Blizzard_PerksProgram.lua:5
 modelFadeInTimer = <userdata>
 SetLabelFont = <function> defined @Blizzard_PerksProgram/Blizzard_PerksProgram.lua:47
 ConfirmRefund = <function> defined @Blizzard_PerksProgram/Blizzard_PerksProgram.lua:302
 GetLabelFont = <function> defined @Blizzard_PerksProgram/Blizzard_PerksProgram.lua:43
 SetSortAscending = <function> defined @Blizzard_PerksProgram/Blizzard_PerksProgram.lua:78
 GetCategoryText = <function> defined @Blizzard

**Comment by d4kir92** [comment]
please try v1.6.88

**Comment by rionshin** [comment]
It's working now! Thank you so much for the fast response and fix.
