### ISSUE TITLE
can't move Chatframe 1 to edge

### ISSUE THREAD

**Issue by MHketbi** [d4kir92/MoveAny#32]
i can not move the chatframe 1 to the edge of the  screen with the newest version.

![WowClassic_GoGtGJNOv1](https://github.com/d4kir92/MoveAny/assets/2147851/75e3935b-4efb-47c7-b3c4-3664ecce1acd)

**Comment by MHketbi** [comment]
using Prat 3.0 to hide the buttons on the left, it seems that is why i cant move it?

also i think there was an option to move those buttons around with moveAny but i cant find it?

![WowClassic_V5OlJ88HH4](https://github.com/d4kir92/MoveAny/assets/2147851/ca87dc01-84e0-46c9-9f66-16b7526e70e8)

**Comment by d4kir92** [comment]
yes, you need to enable "chat buttons", should be findable via the search
