### ISSUE TITLE
Tried to call the protected function StatusBar:Show()

### ISSUE THREAD

**Issue by Xorag** [d4kir92/MoveAny#33]
Started seeing this error in the last few recent versions, often when entering combat:

1x [ADDON_ACTION_BLOCKED] AddOn 'MoveAny' tried to call the protected function 'StatusBar:Show()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `Show'
[string "@FrameXML/TextStatusBar.lua"]:86: in function `TextStatusBar_UpdateTextStringWithValues'
[string "@FrameXML/TextStatusBar.lua"]:72: in function `TextStatusBar_UpdateTextString'
[string "@FrameXML/TextStatusBar.lua"]:187: in function `TextStatusBar_OnValueChanged'
[string "@FrameXML/UnitFrame.lua"]:939: in function `UnitFrameHealthBar_OnValueChanged'
[string "@FrameXML/TargetFrame.lua"]:1060: in function <FrameXML/TargetFrame.lua:1059>
[string "=[C]"]: in function `SetValue'
[string "@FrameXML/UnitFrame.lua"]:884: in function <FrameXML/UnitFrame.lua:872>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}

**Comment by Xorag** [comment]
I am only moving:

Target of Target Frame
Totem Timers
Castbar from Target

in my config. thanks!

**Comment by d4kir92** [comment]
Which wow version are you playing?
how can i reproduce that error? :D

**Comment by d4kir92** [comment]
i am not able to reproduce this, must be a combo of settings/addons

**Comment by d4kir92** [comment]
i tried the 3 checkboxes only

**Comment by Xorag** [comment]
I can reproduce it easily with just moveany enabled going into violet hold dungeon in dalaran and just attack some of the npcs. Attached are my character and account config files:

[MoveAny_Account.lua.txt](https://github.com/d4kir92/MoveAny/files/13832226/MoveAny_Account.lua.txt)
[MoveAny_Character.lua.txt](https://github.com/d4kir92/MoveAny/files/13832227/MoveAny_Character.lua.txt)

**Comment by d4kir92** [comment]
![image](https://github.com/d4kir92/MoveAny/assets/23246564/39e27d20-2235-4fe1-b955-bbe74905e323)
damn it :D still no error

**Comment by d4kir92** [comment]
wait now i have one
![image](https://github.com/d4kir92/MoveAny/assets/23246564/22063e1c-bb82-4102-aca4-87242b373563)

**Comment by Xorag** [comment]
Yes that is my error. I just tested deleting my config and there is no error. so there is an issue with my config it seems?

**Comment by Xorag** [comment]
I believe all I am doing is moving the cast bar and target of target frame, and the totem timer is completely hidden.

**Comment by d4kir92** [comment]
v1.6.111 should fix it

**Comment by d4kir92** [comment]
castbar had not the default parent, i made another solution, should work now

**Comment by Xorag** [comment]
seems to be fixed now thanks so much
