### ISSUE TITLE
map window wont move anymore

### ISSUE THREAD

**Issue by pat1812** [d4kir92/MoveAny#34]
hello, great addon! finally could move my achievements window wit this. Only i cant move my map window anymore since i have installed this. I also use blizzmove

**Comment by d4kir92** [comment]
you dont need blizzmove, its implemented in this

**Comment by pat1812** [comment]
just tried with blizzmove deinstalled. works indeed. thanks for your fast answer, sorry for the false report. wasn't aware i didn't need blizzmove anymore:)

**Comment by d4kir92** [comment]
no problem :D
