### ISSUE TITLE
Move: "Archivment, Guild, Statistic" window

### ISSUE THREAD

**Issue by homezonebenny** [d4kir92/MoveAny#35]
I tried to move this window to top left corner, like all other windows:

![image](https://github.com/d4kir92/MoveAny/assets/11474669/dca1af34-6785-423f-9314-61afff28db5c)

But it seems like it's not imlemented into the Addon yet.
Map and everything was possible, thank you!

**Comment by d4kir92** [comment]
Maybe only movable on the side borders?

**Comment by homezonebenny** [comment]
You're right, it works on the right side of the window.
**Closed!**
