### ISSUE TITLE
Unable to scale ObjectiveTrackerFrame

### ISSUE THREAD

**Issue by skjetne** [d4kir92/MoveAny#39]
Seems like the buttons stopped working. Scaling was reset with the last update.

![iShot_2024-07-01_11 48 31](https://github.com/d4kir92/MoveAny/assets/17202764/b6f64c76-217b-4dfe-8f4b-3790bda5d1db)

**Comment by d4kir92** [comment]
fixed today, i think, pls try latest version

**Comment by skjetne** [comment]
This is on 1.6.227 which I updated to today

**Comment by d4kir92** [comment]
k thx for the info

**Comment by d4kir92** [comment]
works for me on cata/retail 
![image](https://github.com/d4kir92/MoveAny/assets/23246564/cc981eab-6125-481a-9043-dfeb68d14558)

not sure why not for you

**Comment by d4kir92** [comment]
any errors?

**Comment by d4kir92** [comment]
k found the problem

**Comment by d4kir92** [comment]
v1.6.228
