### ISSUE TITLE
expansion landing page button

### ISSUE THREAD

**Issue by swallowsoul** [d4kir92/MoveAny#40]
hey, with the new update the addon is showing the expansion landing page button and there's no option to disable it.

**Comment by d4kir92** [comment]
get latest version :D

**Comment by funkydude** [comment]
I'm not sure who exactly asked for this feature to be added, but please turn it off by default. It has already results in multiple complaints for my minimap addon, and will result in many complaints to everyone of other minimap addons and UI packs in general.

**Comment by d4kir92** [comment]
> I'm not sure who exactly asked for this feature to be added, but please turn it off by default. It has already results in multiple complaints for my minimap addon, and will result in many complaints to everyone of other minimap addons and UI packs in general.

in latest build it should be turned off by default

**Comment by d4kir92** [comment]
should be there soon (v1.6.250)

**Comment by funkydude** [comment]
Thank you!!
