### ISSUE TITLE
Invisible window

### ISSUE THREAD

**Issue by ZodPTR** [d4kir92/MoveAny#42]
I have an interesting problem that occurs mostly in raids, but also outdoors, not always, so it's kind of random where and when.
I have this "EventToastManagerFrame" window, if I drag another window on top of it, nothing will be clickable on it, but the most annoying thing is that I can't select mobs in raid if they are located in that area.
if I turn off moveany and turn on blizzmove, this problem does not occur there

![kép](https://github.com/user-attachments/assets/4b9cf375-56d4-4556-b73c-a61b4f969f21)

**Comment by ZodPTR** [comment]
it may not be the EventToastManagerFrame that is the problem, because now in raid the top of the raid did not detect any clicks where the ZoneText is, but it may be that it is not related to any window, that it is caused by something else, one thing is for sure, when MoveAny is running, there are non-clickable areas at the top of the screen

![kép](https://github.com/user-attachments/assets/c2f06e4d-8124-44bc-9b42-da1f04736946)

**Comment by d4kir92** [comment]
can you do in chat:
/fstack
and then put the mouse where it blocks your mouse, then send me screenshot of it

**Comment by ZodPTR** [comment]
this is a fairly large area usually where the mouse is not detected, about the area shown in the picture

![cc](https://github.com/user-attachments/assets/ee2df242-8cb0-4681-b652-d6a88ad5ac02)

**Comment by d4kir92** [comment]
yes, that area works for me, thats why i need that screenshot :D

**Comment by ZodPTR** [comment]
yes, sometimes it works for me, when I did the printscreen it was fine, but in raid or special places or random, I don't know, sometimes it doesn't work

**Comment by d4kir92** [comment]
UiWidet Top Center is not enabled in moveany?
and Ui Power bar?

**Comment by d4kir92** [comment]
v1.7.60
