### ISSUE TITLE
Bug Report: Issue Saving Profile in MoveAny Addon

### ISSUE THREAD

**Issue by Ci303** [d4kir92/MoveAny#44]
**Issue Description:**  
When attempting to save a profile within the MoveAny addon, the following error occurs, preventing the profile from being saved:

```
3x ...ddOns/Blizzard_EditMode/Mainline/EditModeManager.lua:1273: attempt to index field 'highestLayoutIndexByType' (a nil value)
[string "@Blizzard_EditMode/Mainline/EditModeManager.lua"]:1273: in function `MakeNewLayout'
[string "@Blizzard_EditMode/Mainline/EditModeDialogs.lua"]:44: in function <...ddOns/Blizzard_EditMode/Mainline/EditModeDialogs.lua:37>
[string "=(tail call)"]: ?
[string "@Blizzard_SharedXML/Mainline/SharedUIPanelTemplates.lua"]:1073: in function <...izzard_SharedXML/Mainline/SharedUIPanelTemplates.lua:1069>
```

**Steps to Reproduce:**
1. Open the MoveAny addon.
2. Attempt to save a profile (e.g., a layout named "GoodBase").
3. Observe the error message preventing the save operation.

**Expected Result:**  
The profile should be saved successfully without any errors.

**Actual Result:**  
An error occurs, and the profile is not saved. The error log indicates an issue with the function `MakeNewLayout` in the `EditModeManager.lua` file, specifically with the field `highestLayoutIndexByType`, which appears to be `nil`.

**Error Details:**
- **File:** `Blizzard_EditMode/Mainline/EditModeManager.lua`
- **Line:** 1273
- **Error:** `attempt to index field 'highestLayoutIndexByType' (a nil value)`

**Locals:**
- `self`: Various elements of `EditModeManagerFrame` (e.g., `LayoutDropdown`, `SaveChangesButton`, `GridSpacingSlider`, etc.)
- `newLayoutInfo`: Contains the layout details (`layoutName`, `layoutIndex`, `layoutType`, `systems`)
- **Key Variables:**
  - `layoutType`: 1
  - `layoutName`: "GoodBase"
  - `newLayoutIndex`: `nil`

**Additional Notes:**
The issue appears to stem from an uninitialised or `nil` value in `highestLayoutIndexByType`. This may need to be properly set or initialised before the `MakeNewLayout` function is called to avoid the error.

**Steps Taken to Troubleshoot:**
- Verified that the issue consistently occurs when attempting to save a new layout profile.
- Observed that the issue does not appear to be linked to specific layout settings, suggesting a potential code logic issue in the profile-saving function.

**Reproducibility:**  
Consistently reproducible.

**Potential Workarounds:**  
None identified at this time. Further investigation or a patch may be required to handle the initialisation of `highestLayoutIndexByType`.

**System Information:**
- **Game Version:** [Insert Version]
- **Addon Version:** [Insert Version]
- **Operating System:** [Insert OS]

**Conclusion:**  
A fix is needed to address the `nil` reference in `EditModeManager.lua`. Ensuring `highestLayoutIndexByType` is properly initialised may resolve this issue.

**Comment by d4kir92** [comment]
do you created a custom profile before going to moveany?
or is it not retail?

**Comment by Ci303** [comment]
Hi,  thanks for your reply - I don't believe I made a custom profile first,
and yea, this in the retail.

**Comment by d4kir92** [comment]
v1.7.60
