### ISSUE TITLE
Extra Ability Frame still visible, even when unchecked.

### ISSUE THREAD

**Issue by alpineboi20** [d4kir92/MoveAny#5]
Hi there. I'm not sure if it's just an issue for me, but the Extra Ability frame seems to be visible even when unchecked in the settings menu. 

![Capture](https://user-images.githubusercontent.com/55804568/201937069-d4cf030a-5788-4a4a-b8da-f4b55dc41586.PNG)

**Comment by d4kir92** [comment]
Fixed in v0.8.32

**Comment by alpineboi20** [comment]
Great stuff, Thank You! For the fix.
